backend:
  image:
    repository: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/sausage-backend
    tag: latest
  revisionHistoryLimit: 15
  replicas: 3
  maxUnavailable: 20
  maxSurge: 1
  minAllowed:
    cpu: 0m
    memory: 0Mi
  maxAllowed:
    cpu: 1
    memory: 500Mi

backend-report:
  image:
    repository: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/backend-report
    tag: latest
  revisionHistoryLimit: 15
  minReplicas: 1
  maxReplicas: 5
  averageUtilization: 75

frontend:
  image:
    repository: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/sausage-frontend
    tag: latest
  fqdn: std-013-20.k8s.praktikum-services.tech
  revisionHistoryLimit: 15
