# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault
#   labels:
#     app: vault
# data:
#   vault_token: hvs.CAESIFj7jYZXhwc9HBn70ITUlTBFFcUJ5Wd1Iq_Q1DVhSF0BGh4KHGh2cy54TTJ1RUl0eUNsdXI1T01aOTZzYmxKRlk
# type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4TXkweU1EbzJkVEpVTTJjelRBPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  labels:
    app: backend
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi10eGVuamVvdDBxYmNibmgzLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDEzLTIw
  # REPORT_PATH: Li9sb2dz
  SPRING_DATASOURCE_PASSWORD: UEBzc3cwcmQ=
  SPRING_DATASOURCE_USERNAME: c3RkLTAxMy0yMA==
  # SPRING_DATA_MONGODB_URI: bW9uZ29kYjovL3N0ZC0wMTMtMjA6UCU0MHNzdzByZEByYzFhLXhiNnE3cG13MzZ0NzdyeXoubWRiLnlhbmRleGNsb3VkLm5ldDoyNzAxOC9zdGQtMDEzLTIwP3Rscz10cnVl