---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4TXkweU1EbzJkVEpVTTJjelRBPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{.Chart.Name}}"
  labels:
    app: "{{.Chart.Name}}"
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi10eGVuamVvdDBxYmNibmgzLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDEzLTIw
  SPRING_DATASOURCE_PASSWORD: UEBzc3cwcmQ=
  SPRING_DATASOURCE_USERNAME: c3RkLTAxMy0yMA==