---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  # replicas: 3
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями  
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - image: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/backend-report:latest
          name: backend-report
          imagePullPolicy: IfNotPresent
          env:
            - name: DB
              value: mongodb://std-013-20:P%40ssw0rd@rc1a-xb6q7pmw36t77ryz.mdb.yandexcloud.net:27018/std-013-20?tls=true
            - name: PORT
              value: "8081"
          ports:
            - name: backend-report
              containerPort: 8081
      imagePullSecrets:
            - name: docker-config-secret